### ISSUE TITLE
Language Rules (in TeX)

### ISSUE THREAD

**Issue by scohe001** [wsull001/CS152Proj1#2]
Hey guys,

Just pushed a draft of our language rules and the c++ code I used to make them.

Take a look at the pdf and let me know if it's satisfactory or if we want to do things a little differently. In all honesty, this is minimum effort right now, I could give each rule its own line or add a description at the top for the difference between all caps words and the camel case. Or even italicize one of them to show that it's a terminal or something like that.

Let me know!

EDIT: forgot to mention--it's all in the Language directory

**Comment by wsull001** [comment]
Cool thanks I'll take a look.

**Comment by wsull001** [comment]
It looks good to me.

**Comment by wsull001** [comment]
thanks dude. You wrote a program to do it tho lol was it that much easier?

**Comment by scohe001** [comment]
Lol gotta pull my own weight since this is all your guys' code for part 1 and most of part 2.

Program made it a little easier, but if we decide to change the formatting or add things it'll be a LOT easier now.

**Comment by pgior001** [comment]
i have spoken
